// Generated by kicadtoverilog.py

module divby3test(
    input OSCINPUT,
    output CLK6502);

    // Net definitions
    wire net_1;
    wire net_2;
    wire net_3;
    wire net_4;
    wire net_5;
    wire net_6;
    wire net_7;
    wire net_8;
    wire net_9;
    wire net_10;
    wire net_11;
    wire net_12;
    wire net_13;
    wire net_14;
    wire net_15;
    wire net_16;
    wire net_17;
    wire net_18;
    wire net_19;
    wire net_20;

    // Input pins
    assign net_1 = OSCINPUT;

    // Internal blocks
    NOR2 U18(.A(net_10), .B(net_6), .Y(net_9));
    NOR2 U8(.A(net_2), .B(net_17), .Y(net_8));
    NOR2 U14(.A(net_4), .B(net_7), .Y(net_5));
    NOR2 U9(.A(net_7), .B(net_2), .Y(net_15));
    NOR2 U19(.A(net_9), .B(net_19), .Y(net_6));
    AND2 U20(.A(net_1), .B(net_9), .Y(net_13));
    NOR2 U16(.A(net_1), .B(net_16), .Y(net_10));
    NOR2 U6(.A(net_1), .B(net_3), .Y(net_17));
    NOR2 U13(.A(net_14), .B(net_20), .Y(net_4));
    NOR2 U12(.A(net_11), .B(net_4), .Y(net_14));
    NOR2 U23(.A(net_7), .B(net_12), .Y(net_3));
    AND2 U21(.A(net_6), .B(net_1), .Y(net_12));
    NOR2 U7(.A(net_18), .B(net_8), .Y(net_2));
    AND2 U11(.A(net_8), .B(net_1), .Y(net_20));
    NOT U15(.A(net_5), .Y(net_16));
    AND2 U10(.A(net_1), .B(net_2), .Y(net_11));
    NOR2 U17(.A(net_1), .B(net_5), .Y(net_19));
    NOR2 U5(.A(net_7), .B(net_1), .Y(net_18));
    NOR2 U22(.A(net_13), .B(net_3), .Y(net_7));

    // Output pins
    assign CLK6502 = net_15;
endmodule
