// Generated by kicadtoverilog.py

module inv(
    output Y,
    input A);

    // Net definitions
    wire net_1;
    wire net_2;

    // Input pins
    assign net_2 = A;

    // Internal blocks
    NOT U4(.A(net_2), .Y(net_1));

    // Output pins
    assign Y = net_1;
endmodule
