// Generated by kicadtoverilog.py

module TestIC(
    output not_Q,
    input CLK,
    output Q);

    // Net definitions
    wire net_1;
    wire net_2;
    wire net_3;
    wire net_4;
    wire net_5;

    // Input pins
    assign net_3 = CLK;

    // Internal blocks
    NOR2 U1(.A(net_3), .B(net_2), .Y(net_1));
    NOR2 U2(.A(net_1), .B(net_3), .Y(net_2));
    inv inv1(.A(net_1), .Y(net_4));
    inv inv2(.A(net_2), .Y(net_5));

    // Output pins
    assign not_Q = net_5;
    assign Q = net_4;
endmodule
